services:
  save-file-converter:
    build: .
    container_name: save-file-converter
    ports:
      - "8081:8081"
    volumes:
      - ./.config:/root/.config
      - ./save-file-converter:/app/save-file-converter
    restart: always
