version: "3.9"

services:
  # ==========================================================
  # Crayola app
  # ==========================================================
  http-crayola:
    image: nginx:latest
    container_name: crayola-app
    build: .
    ports:
      - "8082:80"
    environment:
      TARGET_URL: "www.crayola.com"
      YEAR: "1996"
    volumes:
      - ./data:/data
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]