version: "3.9"

services:
  wayback_host:
    build: .
    container_name: wayback_host
    environment:
      TARGET_URL: "http://www.crayola.com/"
      FROM_TS: "19960101"
      TO_TS:   "19961231"
    volumes:
      - ./downloads:/data
    ports:
      - "8082:80"