version: "3.9"

services:
  http-crayola:
    image: nginx:alpine
    container_name: crayola-app
    ports:
      - "8082:80"
    environment:
      TARGET_URL: "www.crayola.com"
      YEAR: "1996"
    volumes:
      - ./data:/usr/share/nginx/html
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
